SELECT TOP (1000) [Id]
      ,[START]
      ,[STOP]
      ,[PATIENT]
      ,[ENCOUNTER]
      ,[CODE]
      ,[DESCRIPTION]
      ,[REASONCODE]
      ,[REASONDESCRIPTION]
  FROM [Emade_Dev].[dbo].[careplans]
